# Generated by Django 5.1.6 on 2025-05-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleTrackerApp', '0002_phonetrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonetrack',
            name='speed',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
