# Generated by Django 5.1.6 on 2025-05-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleTrackerApp', '0003_phonetrack_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonetrack',
            name='battery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonetrack',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
