# Generated by Django 5.1.6 on 2025-05-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleTrackerApp', '0004_phonetrack_battery_phonetrack_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetrack',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
