# Generated by Django 5.1.6 on 2025-05-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleTrackerApp', '0005_alter_phonetrack_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
