# Generated by Django 5.1.6 on 2025-05-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleTrackerApp', '0006_phone_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonetrack',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
