# Generated by Django 5.1.6 on 2025-05-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleTrackerApp', '0007_phonetrack_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetrack',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
