# Generated by Django 5.0.7 on 2024-08-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=140)),
                ('ddd', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='project')),
            ],
        ),
    ]
