# Generated by Django 5.0.7 on 2024-08-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ddd',
        ),
    ]
